[package]
name = "hampi-examples"
version = "0.0.0"
authors = ["Abhijit Gadgil <gabhijit@iitbombay.org>"]
edition = "2018"
publish = false


[dev-dependencies]
asn1-codecs = { path = "../codecs" }
asn1_codecs_derive = { path = "../codecs_derive" }
trybuild = { version = "1.0" }
hex = "*"
bitvec = { version = "0.22" }
log = { version = "0.4.3" }
criterion = { version = "0.3" }
env_logger = "*"

[[bench]]
name = "ngap_bench"
harness = false
